config/routes.rb
Rails.application.routes.draw do



  resources :selfie_verifications, :except => [:index, :destroy]
  resources :address_verifications, :except => [:index, :destroy]
  resources :nationalid_verifications, :except => [:index, :destroy]
  resources :user_infos, :only => [:show, :create, :update]
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :watchdogs
      resources :users
      resources :countries
      resources :affilate_programs
      post "users/create" => "users#create"
      get "homepage" => "users#homepage"
      post "confirmmail" => "users#confirmmail"
      post "resend_confirmmail" => "users#resend_confirmmail"
      get "two_factor" => "users#get_two_factor"
      post "two_factor" => "users#post_two_factor"
      get "send_confirmation_email" => "users#send_confirmation_email"
      get "change_confirmation_code" => "users#change_confirmation_code"
      get "confirm_google_code" => "users#confirm_google_code"
      get "user_log" => "watchdogs#user_log"
      get "active_sessions" => "logins#active_sessions"
      post 'auth_user' => 'authentication#authenticate_user'
      post "unlockaccount" => "authentication#unlockaccount"
      post "send_invitation_email" => "affilate_programs#send_invitation_email"
      post 'getEditToken' => 'authentication#getEditToken'
    end
  end



  resources :affilate_programs, :only => [:create, :destroy]
  resources :countries, :only => [:index, :show]
  resources :logins, :only => [:create, :show, :destroy]
  resources :verifications, :only => [:create, :update, :destroy]
  resources :watchdogs, :only => [:create, :show, :destroy]
  resources :users, :except => [:index]
  root "users#homepage"
  get "confirmmail" => "users#confirmmail"
  get "unlockaccount" => "users#unlockaccount"
  get "two_factor" => "users#get_two_factor"
  post "two_factor" => "users#post_two_factor"
  get "user_log" => "watchdogs#user_log"
  get "active_sessions" => "logins#active_sessions"
  get "send_confirmation_email" => "users#send_confirmation_email"
  get "change_confirmation_code" => "users#change_confirmation_code"
  get "confirm_google_code" => "users#confirm_google_code"
  #get "set_otp_code" => "users#set_otp_code"
  get "affilate-program/:refered_by" => "affilate_programs#set_invitation_code"
  post "send_invitation_email" => "affilate_programs#send_invitation_email"
  get "edit_password/:id" => "users#edit_password" , :as => "edit_password" 
  get "error_page" => "logins#error_page"
  get "lock_page" => "logins#lock_page"
  post "lock_page" => "logins#check_to_unlock"
  
  #match '*path', to: "logins#error_page", via: :all



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user_info.rb
class UserInfo < ApplicationRecord
    belongs_to :user ,:foreign_key => "user_id"
    belongs_to :selfie_verification ,:foreign_key => "selfie_verification_id", optional: true
    belongs_to :nationalid_verification ,:foreign_key => "nationalid_verification_id", optional: true
    belongs_to :address_verification ,:foreign_key => "address_verification_id", optional: true

    enum status: { UnVerified: 0, Verified: 1 }
end

app/controllers/user_infos_controller.rb
class UserInfosController < ApplicationController
  before_action :set_user_info, only: [:show, :edit, :update, :destroy]
  before_action :require_login

  # show details of Verification infos for a specific user
  # @param [Integer] id 
  # @return [String] username
  # @return [String] mobile
  # @return [Integer] address_verification_id
  # @return [Integer] nationalid_verification_id
  # @return [Integer] selfie_verification_id
  # @return [Integer] Status
  # @return [datetime] created_at
  # @return [datetime] updated_at 
  def show
    @user_infos = UserInfo.where("id =?", params[:id]).includes(:selfie_verification, :nationalid_verification, :address_verification)
    if current_user.id != @user_info.user_id.to_i 
      redirect_to root_path , notice: "not allowed" 
    end
  end
  
  def create
    @user_info = UserInfo.new(user_info_params)

    respond_to do |format|
      if @user_info.save
        format.html { redirect_to @user_info, notice: 'User info was successfully created.' }
        format.json { render :show, status: :created, location: @user_info }
      else
        format.html { render :new }
        format.json { render json: @user_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # edit User Info status
  # @param [Integer] id
  # @param [String] mobile
  # @param [Integer] address_verification_id
  # @param [Integer] nationalid_verification_id
  # @param [Integer] selfie_verification_id
  # @param [Integer] nationalid_verification_id
  # @param [Integer] status  
  # @return [Integer] id
  # @return [String] mobile
  # @return [Integer] address_verification_id
  # @return [Integer] nationalid_verification_id
  # @return [Integer] selfie_verification_id
  # @return [Integer] Status
  # @return [datetime] created_at
  # @return [datetime] updated_at
  def update
    respond_to do |format|
      if @user_info.update(user_info_params)
        format.html { redirect_to @user_info, notice: 'User info was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_info }
      else
        format.html { render :edit }
        format.json { render json: @user_info.errors, status: :unprocessable_entity }
      end
    end
  end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_info
      @user_info = UserInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_info_params
      params.require(:user_info).permit(:user_id, :mobile, :address_verification_id, :nationalid_verification_id, :selfie_verification_id, :status)
    end
end

app/helpers/user_infos_helper.rb
module UserInfosHelper
end

app/views/user_infos_/_form.html.erb
<%= form_with(model: user_info, local: true) do |form| %>
  <% if user_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_info.errors.count, "error") %> prohibited this user_info from being saved:</h2>

      <ul>
      <% user_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @nationalid_verified == nil %>
     <%= form.hidden_field :document_type , :value => "NationalId" %>                      
    <div class="field">                                   
      <%= form.select :nationalid_type, options_for_select([["بطاقة الرقم القومى","NationalId_Card"],["جواز السفر","Passport"]]),:include_blank =>  t('choose from list')%>
      </div> 
    <br> 
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    <br> 
    <div class="field">
      <%= form.label :nationalid_no %>
      <%= form.number_field :nationalid_no %>
    </div>
    <br> 
    <div class="field">
      <%= form.label :issue_date %>
      <%= form.date_select :issue_date %>
    </div>
    <br> 
    <div class="field">
      <%= form.label :expire_date %>
      <%= form.date_select :expire_date %>
    </div>
    <br>
    <div class="field">
      <%= form.label :attachment %>
      <%= form.file_field :attachment %>
    </div>
    <br> 
    <div class="actions">
      <%= form.submit %>
    </div>



  <% elsif @selfie_verified == nil %>
  <%= form.hidden_field :document_type , :value => "Selfi" %> 

    <div class="field">
      <%= form.label :attachment %>
      <%= form.file_field :attachment %>
      <br> 
    <div class="actions">
      <%= form.submit %>
    </div>

    </div>


  <% elsif @address_verified == nil %>
  <%= form.hidden_field :document_type , :value => "Address" %> 

    <div class="field">
      <%= form.label :address %>
      <%= form.text_field :address %>
    </div>
    <br>
    <div class="field">
      <%= form.label :attachment %>
      <%= form.file_field :attachment %>
    </div><br>
    <div class="actions">
      <%= form.submit %>
    </div>



  <% end %>
  


<% end %>

app/views/user_infos_/create.html.erb
<%= debug params[:user_info][:document_type]%>

app/views/user_infos_/edit.html.erb
<h1>Editing User Info</h1>

<%= render 'form', user_info: @user_info %>

<%= link_to 'Show', @user_info %> |
<%= link_to 'Back', user_infos_path %>

app/views/user_infos_/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Infos</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Issue date</th>
      <th>Expire date</th>
      <th>Nationalid no</th>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_infos.each do |user_info| %>
      <tr>
        <td><%= user_info.user.username %></td>
        <td><%= user_info.issue_date %></td>
        <td><%= user_info.expire_date %></td>
        <td><%= user_info.nationalid_no %></td>
        <td><%= user_info.name %></td>
        <td><%= user_info.address %></td>
        <td><%= link_to 'Show', user_info %></td>
        <td><%= link_to 'Edit', edit_user_info_path(user_info) %></td>
        <td><%= link_to 'Destroy', user_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Info', new_user_info_path %>

app/views/user_infos_/new.html.erb
<h1>New User Info</h1>

<%= render 'form', user_info: @user_info %>

<%= link_to 'Back', user_infos_path %>

app/views/user_infos_/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_info.user.username %>
</p>

<p>
  <strong>Document Type:</strong>
  <%= @user_info.user_verification.document_type %>
</p>

<% if @user_info.user_verification.document_type == "NationalId" %>
<p>
  <strong>Issue date:</strong>
  <%= @user_info.issue_date %>
</p>

<p>
  <strong>Expire date:</strong>
  <%= @user_info.expire_date %>
</p>

<p>
  <strong>Nationalid no:</strong>
  <%= @user_info.nationalid_no %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user_info.name %>
</p>
<% elsif @user_info.user_verification.document_type == "Address" %>

<p>
  <strong>Address:</strong>
  <%= @user_info.address %>
</p>

<% end %>

<p>
  <strong>attachment:</strong>
  <%= image_tag @user_info.attachment.variant(resize: "100x100")  %>
</p>


<%= form_with(model: @user_info.user_verification, local: true) do |form| %>


  <div class="field">                                   
      <%= form.select :status, options_for_select([["UnVerified","UnVerified"],["Verified","Verified"]], :selected => form.object.status ),:include_blank =>  t('choose from list')%>
      </div> 
  <br> 

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

<%= link_to 'Edit', edit_user_info_path(@user_info) %> |
<%= link_to 'Back', user_infos_path %>