config/routes.rb
Rails.application.routes.draw do



  resources :selfie_verifications, :except => [:index, :destroy]
  resources :address_verifications, :except => [:index, :destroy]
  resources :nationalid_verifications, :except => [:index, :destroy]
  resources :user_infos, :only => [:show, :create, :update]
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :watchdogs
      resources :users
      resources :countries
      resources :affilate_programs
      post "users/create" => "users#create"
      get "homepage" => "users#homepage"
      post "confirmmail" => "users#confirmmail"
      post "resend_confirmmail" => "users#resend_confirmmail"
      get "two_factor" => "users#get_two_factor"
      post "two_factor" => "users#post_two_factor"
      get "send_confirmation_email" => "users#send_confirmation_email"
      get "change_confirmation_code" => "users#change_confirmation_code"
      get "confirm_google_code" => "users#confirm_google_code"
      get "user_log" => "watchdogs#user_log"
      get "active_sessions" => "logins#active_sessions"
      post 'auth_user' => 'authentication#authenticate_user'
      post "unlockaccount" => "authentication#unlockaccount"
      post "send_invitation_email" => "affilate_programs#send_invitation_email"
      post 'getEditToken' => 'authentication#getEditToken'
    end
  end



  resources :affilate_programs, :only => [:create, :destroy]
  resources :countries, :only => [:index, :show]
  resources :logins, :only => [:create, :show, :destroy]
  resources :verifications, :only => [:create, :update, :destroy]
  resources :watchdogs, :only => [:create, :show, :destroy]
  resources :users, :except => [:index]
  root "users#homepage"
  get "confirmmail" => "users#confirmmail"
  get "unlockaccount" => "users#unlockaccount"
  get "two_factor" => "users#get_two_factor"
  post "two_factor" => "users#post_two_factor"
  get "user_log" => "watchdogs#user_log"
  get "active_sessions" => "logins#active_sessions"
  get "send_confirmation_email" => "users#send_confirmation_email"
  get "change_confirmation_code" => "users#change_confirmation_code"
  get "confirm_google_code" => "users#confirm_google_code"
  #get "set_otp_code" => "users#set_otp_code"
  get "affilate-program/:refered_by" => "affilate_programs#set_invitation_code"
  post "send_invitation_email" => "affilate_programs#send_invitation_email"
  get "edit_password/:id" => "users#edit_password" , :as => "edit_password" 
  get "error_page" => "logins#error_page"
  get "lock_page" => "logins#lock_page"
  post "lock_page" => "logins#check_to_unlock"
  
  #match '*path', to: "logins#error_page", via: :all



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/login.rb
class Login < ApplicationRecord
  belongs_to :user,:foreign_key => "user_id"
end

app/controllers/api/v1/logins_controller.rb
class Api::V1::LoginsController < ApplicationController
  #before_action :require_login
  before_action :set_login, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_request!
  skip_before_action :verify_authenticity_token
  attr_reader :current_user

  # GET /logins
  # GET /logins.json
  def index
    if current_user.roleid == 1
      @logins = Login.all
      else
        redirect_to root_path , notice: "not allowed" 
    end   
  end


      # show user's active sessions
      # GET /active_sessions
      #=begin
      # @api {get} /api/v1/active_sessions?id={:user-id} show user's active sessions
      # @apiVersion 0.3.0
      # @apiName Getactivesessions
      # @apiGroup Log
      # @apiDescription show user's active sessions.
      # @apiExample Example usage:
      # curl -i http://localhost:3000/api/v1/active_sessions?id=1 -H "Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo5fQ.xM_NrnhjjJejtZFatkVZWAZS_BFxvtjBns50IdcakzU"
      #
      # @apiSuccess {Integer}     id                    Users-ID.
      # @apiSuccess {Integer}     ipaddress             Ip address
      # @apiSuccess {String}      user_agent            Session Details	.
      # @apiSuccess {String}      device_id             device id
      # @apiSuccess {Datetime}    created_at            Date of creating the session.
      # @apiSuccess {Datetime}    updated_at            Date of updating the session.
      #
      # @apiError NoAccessRight Only authenticated users can perform this action.
      #
      # @apiErrorExample Response (example):
      #     HTTP/1.1 401 Unauthorized
      #     {
      #       "error": "NoAccessRight"
      #    }
      #=end

  def active_sessions
      @logins = Login.where("user_id =? ",params[:id])
      respond_to do |format|
          if current_user.roleid == 1 or current_user.id == params[:id].to_i
             format.json { render json: @logins }
          else
              format.json { render json: "Not Allowed" }
          end 
      end
  end

  # GET /logins/1
  # GET /logins/1.json
  def show
    if current_user.roleid != 1 and current_user.id != params[:id].to_i 
      redirect_to root_path , notice: "not allowed" 
    end
  end

  # GET /logins/new
  def new
    if current_user.roleid == 1 
      @login = Login.new
    else
      redirect_to root_path , notice: "not allowed" 
    end
    
  end

  # GET /logins/1/edit
  def edit
    if current_user.roleid != 1 
      redirect_to root_path , notice: "not allowed" 
    end
  end

  # POST /logins
  # POST /logins.json
  def create
    @login = Login.new(login_params)

    respond_to do |format|
      if @login.save
        format.html { redirect_to @login, notice: 'Login was successfully created.' }
        format.json { render :show, status: :created, location: @login }
      else
        format.html { render :new }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logins/1
  # PATCH/PUT /logins/1.json
  def update
    if current_user.roleid != 1 
      redirect_to root_path , notice: "not allowed" 
    else
     respond_to do |format|
       if @login.update(login_params)
         format.html { redirect_to @login, notice: 'Login was successfully updated.' }
         format.json { render :show, status: :ok, location: @login }
       else
         format.html { render :edit }
         format.json { render json: @login.errors, status: :unprocessable_entity }
       end
     end
    end
  end

  # DELETE /logins/1
  # DELETE /logins/1.json
  def destroy
    if current_user.roleid != 1 
      redirect_to root_path , notice: "not allowed" 
    else
      @login.destroy
      cookies.delete(:auth_token)
      cookies.delete(:device_id)
      sign_out
      respond_to do |format|
        format.html { redirect_to logins_url, notice: 'Login was successfully destroyed.' }
        format.json { head :no_content }
      end
    end      
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_login
      @login = Login.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def login_params
      params.require(:login).permit(:user_id, :ip_address, :user_agent, :device_id)
    end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  before_action :require_login
  before_action :set_login, only: [:show, :edit, :update, :destroy]

  
  # show user's active sessions
  # works only if current user is an admin
  # @param [Integer] user_id
  def active_sessions
    if current_user.id == params[:id].to_i
      @logins = Login.where("user_id =? ",params[:id])
    else
      redirect_to root_path , notice: "not allowed" 
    end
  end

  # show details of a log
  # @param [Integer] id
  # @return [Integer] user_id
  # @return [String] ip_address
  # @return [String] user_agent	
  # @return [String] device_id
  # @return [String] operation_type	
  # @return [datetime] created_at
  # @return [datetime] updated_at
  def show
    if current_user.id != params[:id].to_i 
      redirect_to root_path , notice: "not allowed" 
    end
  end

  # create new login
  # @param [Integer] user_id
  # @param [String] ip_address
  # @param [String] user_agent	
  # @param [String] device_id
  # @param [String] operation_type
  # @return [Integer] id
  # @return [Integer] user_id
  # @return [String] ip_address
  # @return [String] user_agent	
  # @return [String] device_id
  # @return [String] operation_type	
  # @return [datetime] created_at
  # @return [datetime] updated_at
  def create
    @login = Login.new(login_params)

    respond_to do |format|
      if @login.save
        format.html { redirect_to @login, notice: 'Login was successfully created.' }
        format.json { render :show, status: :created, location: @login }
      else
        format.html { render :new }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # destroy login
  # @param [Integer] id
  
  def destroy
      @login.destroy
      #cookies.delete(:auth_token)
      #cookies.delete(:device_id)
      #sign_out
      respond_to do |format|
        format.html { redirect_to logins_url, notice: 'Login was successfully destroyed.' }
        format.json { head :no_content }
      end     
  end

  def error_page
    render :layout => false
  end

  def lock_page
    render :layout => false
  end

  def check_to_unlock
    @user = User.authenticate(current_user.email,params[:unlock][:password])
    if !(@user)  
      @user_sessions = Login.where(user_id: current_user.id).all
        if (@user_sessions  != nil)
          @user_sessions.all.each do |user_sessions|
              user_sessions.destroy
          end
        end
      cookies.delete(:auth_token)
      cookies.delete(:device_id)
      session[:refered_by] = nil
      session[:last_visit] = nil
      sign_out
      redirect_to sign_in_path 
         #redirect_to lock_page_path , notice: "wrong password"   
    else
      session[:last_visit] = Time.now
      redirect_to root_path , notice: "welcome again!"   
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_login
      @login = Login.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def login_params
      params.require(:login).permit(:user_id, :ip_address, :user_agent, :device_id)
    end
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/logins/_form.html.erb
<%= form_with(model: login, local: true) do |form| %>
  <% if login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(login.errors.count, "error") %> prohibited this login from being saved:</h2>

      <ul>
      <% login.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :ip_address %>
    <%= form.text_field :ip_address %>
  </div>

  <div class="field">
    <%= form.label :user_agent %>
    <%= form.text_field :user_agent %>
  </div>

  <div class="field">
    <%= form.label :device_id %>
    <%= form.text_field :device_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/logins/active_sessions.html.erb
<p id="notice"><%= notice %></p>

<h1>Logins</h1>

<table>
  <thead>
    <tr>
     
      <th>Ip address</th>
      <th>User agent</th>
      <th>Device</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @logins.each do |login| %>
      <tr>
       
        <td><%= login.ip_address %></td>
        <td><%= login.user_agent %></td>
        <td><%= login.device_id %></td>
        <td><%= link_to 'Show', login %></td>
        <td>
           <% if login.device_id == cookies[:device_id] %>
             Current session
           <% else %>
              <%# link_to "<i class='fa fa-remove'></i>".html_safe, login_path(login), method: :delete, remote: true, title: "Sign out", data: { confirm: "Are you sure you want to sign out from this device?" } %>
              <%# link_to 'Destroy', login, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Login', new_login_path %>

app/views/logins/edit.html.erb
<h1>Editing Login</h1>

<%= render 'form', login: @login %>

<%= link_to 'Show', @login %> |
<%= link_to 'Back', logins_path %>

app/views/logins/error_page.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Payers | Payment Facilator</title>
  <meta name="description" content="Admin, Dashboard, Bootstrap, Bootstrap 4, Angular, AngularJS" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimal-ui" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <!-- for ios 7 style, multi-resolution icon of 152x152 -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-barstyle" content="black-translucent">
  <link rel="apple-touch-icon" href="../assets/images/logo.png">
  <meta name="apple-mobile-web-app-title" content="Payers">
  <!-- for Chrome on Android, multi-resolution icon of 196x196 -->
  <meta name="mobile-web-app-capable" content="yes">
  <link rel="shortcut icon" sizes="196x196" href="/assets/images/logo.png">
  
  <!-- style -->
  <link rel="stylesheet" href="/assets/animate.css/animate.min.css" type="text/css" />
  <link rel="stylesheet" href="/assets/glyphicons/glyphicons.css" type="text/css" />
  <link rel="stylesheet" href="/assets/font-awesome/css/font-awesome.min.css" type="text/css" />
  <link rel="stylesheet" href="/assets/material-design-icons/material-design-icons.css" type="text/css" />

  <link rel="stylesheet" href="/assets/bootstrap/dist/css/bootstrap.min.css" type="text/css" />
  <!-- build:css ../assets/styles/app.min.css -->
  <link rel="stylesheet" href="/assets/styles/app.css" type="text/css" />
  <!-- endbuild -->
  <link rel="stylesheet" href="/assets/styles/font.css" type="text/css" />
</head>
<body>
  <div class="app" id="app">

<!-- ############ LAYOUT START-->
<div class="app-footer white">
<!-- <div ui-include="'/views/blocks/footer.html'"></div> -->
</div>
<div class="app-body amber bg-auto w-full">
  <div class="text-center pos-rlt p-y-md">
    <h1 class="text-shadow m-0 text-white text-4x">
      <span class="text-2x font-bold block m-t-lg">404</span>
    </h1>
    <h2 class="h1 m-y-lg text-black">OOPS!</h2>
    <p class="h5 m-y-lg text-u-c font-bold text-black">Sorry! the page you are looking for doesn't exist.</p>
    <a href="/" ui-sref="app.dashboard" class="md-btn amber-700 md-raised p-x-md">
      <span class="text-white">Go to the home page</span>
    </a>
  </div>
</div>

<!-- ############ LAYOUT END-->

  </div>
<!-- build:js scripts/app.html.js -->
<!-- jQuery -->
  <script src="/libs/jquery/jquery/dist/jquery.js"></script>
<!-- Bootstrap -->
  <script src="/libs/jquery/tether/dist/js/tether.min.js"></script>
  <script src="/libs/jquery/bootstrap/dist/js/bootstrap.js"></script>
<!-- core -->
  <script src="/libs/jquery/underscore/underscore-min.js"></script>
  <script src="/libs/jquery/jQuery-Storage-API/jquery.storageapi.min.js"></script>
  <script src="/libs/jquery/PACE/pace.min.js"></script>

  <script src="scripts/config.lazyload.js"></script>

  <script src="scripts/palette.js"></script>
  <script src="scripts/ui-load.js"></script>
  <script src="scripts/ui-jp.js"></script>
  <script src="scripts/ui-include.js"></script>
  <script src="scripts/ui-device.js"></script>
  <script src="scripts/ui-form.js"></script>
  <script src="scripts/ui-nav.js"></script>
  <script src="scripts/ui-screenfull.js"></script>
  <script src="scripts/ui-scroll-to.js"></script>
  <script src="scripts/ui-toggle-class.js"></script>

  <script src="scripts/app.js"></script>

  <!-- ajax -->
  <script src="/libs/jquery/jquery-pjax/jquery.pjax.js"></script>
  <script src="scripts/ajax.js"></script>
<!-- endbuild -->
</body>
</html>

app/views/logins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Logins</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Ip address</th>
      <th>User agent</th>
      <th>Device</th>
      <th>Details</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logins.each do |login| %>
      <tr>
        <td><%= login.user.username %></td>
        <td><%= login.ip_address %></td>
        <td><%= login.user_agent %></td>
        <td><%= login.device_id %></td>
        <td><%= login.operation_type %></td>
        <td><%= link_to 'Show', login %></td>
        <td><%= link_to 'Edit', edit_login_path(login) %></td>
        <td><%= link_to 'Destroy', login, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Login', new_login_path %>

app/views/logins/lock_page.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Payers | Payment Facilator</title>
  <meta name="description" content="Admin, Dashboard, Bootstrap, Bootstrap 4, Angular, AngularJS" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimal-ui" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <!-- for ios 7 style, multi-resolution icon of 152x152 -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-barstyle" content="black-translucent">
  <link rel="apple-touch-icon" href="../assets/images/logo.png">
  <meta name="apple-mobile-web-app-title" content="Payers">
  <!-- for Chrome on Android, multi-resolution icon of 196x196 -->
  <meta name="mobile-web-app-capable" content="yes">
  <link rel="shortcut icon" sizes="196x196" href="../assets/images/logo.png">
  
  <!-- style -->
  <link rel="stylesheet" href="/assets/animate.css/animate.min.css" type="text/css" />
  <link rel="stylesheet" href="/assets/glyphicons/glyphicons.css" type="text/css" />
  <link rel="stylesheet" href="/assets/font-awesome/css/font-awesome.min.css" type="text/css" />
  <link rel="stylesheet" href="/assets/material-design-icons/material-design-icons.css" type="text/css" />

  <link rel="stylesheet" href="/assets/bootstrap/dist/css/bootstrap.min.css" type="text/css" />
  <!-- build:css ../assets/styles/app.min.css -->
  <link rel="stylesheet" href="/assets/styles/app.css" type="text/css" />
  <!-- endbuild -->
  <link rel="stylesheet" href="/assets/styles/font.css" type="text/css" />
</head>
<body>
  <div class="app" id="app">

<!-- ############ LAYOUT START-->

<div class="indigo-800 h-v row-col">
  <div class="row-cell v-m text-center animated fadeIn">
    <div class="m-b">
    <% flash.each do |key, value| -%>
        <div class="col-sm-3">
                <div class="box-color accent pos-rlt">
                  <span class="arrow bottom b-accent"></span>
                  <div class="box-body">
                     <div id="flash_<%= key %>"><%=h value %></div>
                  </div>
                </div>
        </div>
      <% end %>
    <%= yield %>
        <% if current_user.avatar.attached? %>
            <%= image_tag(current_user.avatar.variant(resize: "100x100"), :class => "w-64 circle")  %>
        <% else %>
            <img src="/assets/images/blank-profile-pic.png" alt="..." class="w-64 circle">
        <% end %> 
      <div class="m-t-md font-bold"><%= current_user.username%></div>
    </div>
    <%= form_for :unlock , :url => lock_page_path do |f| %>
       <div class="md-form-group w-xl w-auto-xs center-block">
           <%= f.password_field :password , class: 'md-input text-center', :required => true %>
    	   <label class="block w-full">Your Password</label>
       </div>
       <div class="m-t">
           <button type="submit" class="btn btn-danger p-x-md">Unlock</button>
       </div>
    <% end %>
  </div>
</div>

<!-- ############ LAYOUT END-->

  </div>
<!-- build:js scripts/app.html.js -->
<!-- jQuery -->
  <script src="/libs/jquery/jquery/dist/jquery.js"></script>
<!-- Bootstrap -->
  <script src="/libs/jquery/tether/dist/js/tether.min.js"></script>
  <script src="/libs/jquery/bootstrap/dist/js/bootstrap.js"></script>
<!-- core -->
  <script src="/libs/jquery/underscore/underscore-min.js"></script>
  <script src="/libs/jquery/jQuery-Storage-API/jquery.storageapi.min.js"></script>
  <script src="/libs/jquery/PACE/pace.min.js"></script>

  <script src="scripts/config.lazyload.js"></script>

  <script src="scripts/palette.js"></script>
  <script src="scripts/ui-load.js"></script>
  <script src="scripts/ui-jp.js"></script>
  <script src="scripts/ui-include.js"></script>
  <script src="scripts/ui-device.js"></script>
  <script src="scripts/ui-form.js"></script>
  <script src="scripts/ui-nav.js"></script>
  <script src="scripts/ui-screenfull.js"></script>
  <script src="scripts/ui-scroll-to.js"></script>
  <script src="scripts/ui-toggle-class.js"></script>

  <script src="scripts/app.js"></script>

  <!-- ajax -->
  <script src="/libs/jquery/jquery-pjax/jquery.pjax.js"></script>
  <script src="scripts/ajax.js"></script>
<!-- endbuild -->
</body>
</html>

app/views/logins/new.html.erb
<h1>New Login</h1>

<%= render 'form', login: @login %>

<%= link_to 'Back', logins_path %>

app/views/logins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @login.user %>
</p>

<p>
  <strong>Ip address:</strong>
  <%= @login.ip_address %>
</p>

<p>
  <strong>User agent:</strong>
  <%= @login.user_agent %>
</p>

<p>
  <strong>Device:</strong>
  <%= @login.device_id %>
</p>

<%= link_to 'Edit', edit_login_path(@login) %> |
<%= link_to 'Back', logins_path %>