config/routes.rb
Rails.application.routes.draw do



  resources :selfie_verifications, :except => [:index, :destroy]
  resources :address_verifications, :except => [:index, :destroy]
  resources :nationalid_verifications, :except => [:index, :destroy]
  resources :user_infos, :only => [:show, :create, :update]
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :watchdogs
      resources :users
      resources :countries
      resources :affilate_programs
      post "users/create" => "users#create"
      get "homepage" => "users#homepage"
      post "confirmmail" => "users#confirmmail"
      post "resend_confirmmail" => "users#resend_confirmmail"
      get "two_factor" => "users#get_two_factor"
      post "two_factor" => "users#post_two_factor"
      get "send_confirmation_email" => "users#send_confirmation_email"
      get "change_confirmation_code" => "users#change_confirmation_code"
      get "confirm_google_code" => "users#confirm_google_code"
      get "user_log" => "watchdogs#user_log"
      get "active_sessions" => "logins#active_sessions"
      post 'auth_user' => 'authentication#authenticate_user'
      post "unlockaccount" => "authentication#unlockaccount"
      post "send_invitation_email" => "affilate_programs#send_invitation_email"
      post 'getEditToken' => 'authentication#getEditToken'
    end
  end



  resources :affilate_programs, :only => [:create, :destroy]
  resources :countries, :only => [:index, :show]
  resources :logins, :only => [:create, :show, :destroy]
  resources :verifications, :only => [:create, :update, :destroy]
  resources :watchdogs, :only => [:create, :show, :destroy]
  resources :users, :except => [:index]
  root "users#homepage"
  get "confirmmail" => "users#confirmmail"
  get "unlockaccount" => "users#unlockaccount"
  get "two_factor" => "users#get_two_factor"
  post "two_factor" => "users#post_two_factor"
  get "user_log" => "watchdogs#user_log"
  get "active_sessions" => "logins#active_sessions"
  get "send_confirmation_email" => "users#send_confirmation_email"
  get "change_confirmation_code" => "users#change_confirmation_code"
  get "confirm_google_code" => "users#confirm_google_code"
  #get "set_otp_code" => "users#set_otp_code"
  get "affilate-program/:refered_by" => "affilate_programs#set_invitation_code"
  post "send_invitation_email" => "affilate_programs#send_invitation_email"
  get "edit_password/:id" => "users#edit_password" , :as => "edit_password" 
  get "error_page" => "logins#error_page"
  get "lock_page" => "logins#lock_page"
  post "lock_page" => "logins#check_to_unlock"
  
  #match '*path', to: "logins#error_page", via: :all



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/verification.rb
class Verification < ApplicationRecord
    belongs_to :user ,:foreign_key => "user_id"
end

app/controllers/verifications_controller.rb
class VerificationsController < ApplicationController
  before_action :require_login , only: [:show, :edit, :update, :destroy,:index]
  before_action :set_verification, only: [:show, :edit, :update, :destroy]

  # GET /verifications
  # GET /verifications.json
  def index
    @verifications = Verification.all
  end

  # GET /verifications/1
  # GET /verifications/1.json
  def show
  end

  # GET /verifications/new
  def new
    @verification = Verification.new
  end

  # GET /verifications/1/edit
  def edit
  end

  # POST /verifications
  # POST /verifications.json
  def create
    @verification = Verification.new(verification_params)

    respond_to do |format|
      if @verification.save
        format.html { redirect_to @verification, notice: 'Verification was successfully created.' }
        format.json { render :show, status: :created, location: @verification }
      else
        format.html { render :new }
        format.json { render json: @verification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /verifications/1
  # PATCH/PUT /verifications/1.json
  def update
    respond_to do |format|
      if @verification.update(verification_params)
        format.html { redirect_to @verification, notice: 'Verification was successfully updated.' }
        format.json { render :show, status: :ok, location: @verification }
      else
        format.html { render :edit }
        format.json { render json: @verification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /verifications/1
  # DELETE /verifications/1.json
  def destroy
    @verification.destroy
    respond_to do |format|
      format.html { redirect_to verifications_url, notice: 'Verification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_verification
      @verification = Verification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def verification_params
      params.require(:verification).permit(:user_id, :email_confirmation_token, :email_confirmed_at)
    end
end

app/helpers/verifications_helper.rb
module VerificationsHelper
end

app/views/verifications/_form.html.erb
<%= form_with(model: verification, local: true) do |form| %>
  <% if verification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(verification.errors.count, "error") %> prohibited this verification from being saved:</h2>

      <ul>
      <% verification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :email_confirmation_token %>
    <%= form.text_field :email_confirmation_token %>
  </div>

  <div class="field">
    <%= form.label :email_confirmed_at %>
    <%= form.datetime_select :email_confirmed_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/verifications/edit.html.erb
<h1>Editing Verification</h1>

<%= render 'form', verification: @verification %>

<%= link_to 'Show', @verification %> |
<%= link_to 'Back', verifications_path %>

app/views/verifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Verifications</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Email confirmation token</th>
      <th>Email confirmed at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @verifications.each do |verification| %>
      <tr>
        <td><%= verification.user.username %></td>
        <td><%= verification.email_confirmation_token %></td>
        <td><%= verification.email_confirmed_at %></td>
        <td><%= link_to 'Show', verification %></td>
        <td><%= link_to 'Edit', edit_verification_path(verification) %></td>
        <td><%= link_to 'Destroy', verification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Verification', new_verification_path %>

app/views/verifications/new.html.erb
<h1>New Verification</h1>

<%= render 'form', verification: @verification %>

<%= link_to 'Back', verifications_path %>

app/views/verifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @verification.user_id %>
</p>

<p>
  <strong>Email confirmation token:</strong>
  <%= @verification.email_confirmation_token %>
</p>

<p>
  <strong>Email confirmed at:</strong>
  <%= @verification.email_confirmed_at %>
</p>

<%= link_to 'Edit', edit_verification_path(@verification) %> |
<%= link_to 'Back', verifications_path %>