config/routes.rb
Rails.application.routes.draw do



  resources :selfie_verifications, :except => [:index, :destroy]
  resources :address_verifications, :except => [:index, :destroy]
  resources :nationalid_verifications, :except => [:index, :destroy]
  resources :user_infos, :only => [:show, :create, :update]
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :watchdogs
      resources :users
      resources :countries
      resources :affilate_programs
      post "users/create" => "users#create"
      get "homepage" => "users#homepage"
      post "confirmmail" => "users#confirmmail"
      post "resend_confirmmail" => "users#resend_confirmmail"
      get "two_factor" => "users#get_two_factor"
      post "two_factor" => "users#post_two_factor"
      get "send_confirmation_email" => "users#send_confirmation_email"
      get "change_confirmation_code" => "users#change_confirmation_code"
      get "confirm_google_code" => "users#confirm_google_code"
      get "user_log" => "watchdogs#user_log"
      get "active_sessions" => "logins#active_sessions"
      post 'auth_user' => 'authentication#authenticate_user'
      post "unlockaccount" => "authentication#unlockaccount"
      post "send_invitation_email" => "affilate_programs#send_invitation_email"
      post 'getEditToken' => 'authentication#getEditToken'
    end
  end



  resources :affilate_programs, :only => [:create, :destroy]
  resources :countries, :only => [:index, :show]
  resources :logins, :only => [:create, :show, :destroy]
  resources :verifications, :only => [:create, :update, :destroy]
  resources :watchdogs, :only => [:create, :show, :destroy]
  resources :users, :except => [:index]
  root "users#homepage"
  get "confirmmail" => "users#confirmmail"
  get "unlockaccount" => "users#unlockaccount"
  get "two_factor" => "users#get_two_factor"
  post "two_factor" => "users#post_two_factor"
  get "user_log" => "watchdogs#user_log"
  get "active_sessions" => "logins#active_sessions"
  get "send_confirmation_email" => "users#send_confirmation_email"
  get "change_confirmation_code" => "users#change_confirmation_code"
  get "confirm_google_code" => "users#confirm_google_code"
  #get "set_otp_code" => "users#set_otp_code"
  get "affilate-program/:refered_by" => "affilate_programs#set_invitation_code"
  post "send_invitation_email" => "affilate_programs#send_invitation_email"
  get "edit_password/:id" => "users#edit_password" , :as => "edit_password" 
  get "error_page" => "logins#error_page"
  get "lock_page" => "logins#lock_page"
  post "lock_page" => "logins#check_to_unlock"
  
  #match '*path', to: "logins#error_page", via: :all



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
    before_action :authenticate_request!, except: [:create, :confirmmail, :resend_confirmmail]
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    skip_before_action :verify_authenticity_token
    attr_reader :current_user
    
    # GET /users/1
    # GET /users/1.json
    # =begin
    # @api {get} /api/users/{:id} Get User Data
    # @apiVersion 0.3.0
    # @apiName GetUser
    # @apiGroup User
    # @apiDescription get details of specific user.
    # @apiExample Example usage:
    # curl -H "Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMX0.ikUiajq9UFTi4OJDDGR2Xqk79U5vtiRWJaa8HgneqC4" -i http://localhost:3000/api/v1/users/1
    #
    # @apiSuccess {Integer}    id                   Users-ID.
    # @apiSuccess {String}     username             Users username.
    # @apiSuccess {String}     firstname            Users firstname.
    # @apiSuccess {String}     lastname             Users lastname.
    # @apiSuccess {String}     email                Users email.
    # @apiSuccess {Integer}    country_id           Users country.
    # @apiSuccess {Datetime}   created_at           date of creating the User.
    # @apiSuccess {Datetime}   updated_at           date of updating the User.
    #
    # @apiError NoAccessRight Only authenticated users can access the data.
    # @apiError UserNotFound   The <code>id</code> of the User was not found.
    #
    # @apiErrorExample Response (example):
    #     HTTP/1.1 401 Unauthorized
    #     {
    #       "error": "NoAccessRight"
    #    }
    # @apiErrorExample Error-Response:
    #     HTTP/1.1 404 Not Found
    #     {
    #       "error": "UserNotFound"
    #    }
    # =end

  def show    
    @user = User.where("id =? " ,params[:id]).first
      respond_to do |format|
        if current_user.id == params[:id].to_i        
          format.json { render json: @user }
        else
          format.json { render json: "Not Allowed" }
        end
      end
  end
 
  def homepage   
    # curl -H "Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMX0.ikUiajq9UFTi4OJDDGR2Xqk79U5vtiRWJaa8HgneqC4" -H "Content-Type: application/json" -X GET http://localhost:3000/api/v1/homepage
    render json: {'logged_in' => true} 
  end

    # confirm user mail after registeration
    # POST /confirm user mail after registeration
    # =begin
    # @api {post} /api/v1/confirmmail confirm user mail
    # @apiVersion 0.3.0
    # @apiName POSTconfirmmail
    # @apiGroup User
    # @apiDescription confirm user mail after registeration.
    # @apiExample Example usage:
    # curl -X POST  http://localhost:3000/api/v1/confirmmail -H 'cache-control: no-cache' -H 'content-type: application/json' -d '{"email": "engamira333@gmail.com","token": "3aa4e716"}' 
    #
    # @apiSuccessExample Success-Response:
    # HTTP/1.1 200 OK
    # {
    #   "result : true"
    # }
    #
    # @apiError required_parameter_missing wrong code .
    # @apiError required_parameter_missing2 wrong email .
    #
    # @apiErrorExample Response (example):
    #     HTTP/1.1 400 Badrequest
    #     {
    #       "result : false"
    #       "error": "MissingData"
    #       "status": 400- Bad Request
    #    }
    # =end 

  def confirmmail
      @email = params[:email]
      @token = params[:token]
      @user = User.where("email =?",@email ).first
        if @user
           @verify_code = Verification.where("user_id =?",@user.id ).first
           if @verify_code.email_confirmation_token == @token
              @user.update(:status => 1)
              @verify_code.update(:email_confirmed_at => Time.now) 
              render json: {'result' => true}
           else
              render json: {'result' => false, 'error' => 'wrong code'}
           end      
        else
              render json: {'result' => false, 'error' => 'Email Not Found'}
        end
  end

    # resend confirmation mail 
    # POST /resend confirmation mail to user after registeration
    # =begin
    # @api {post} /api/v1/resend_confirmmail resend confirmation mail
    # @apiVersion 0.3.0
    # @apiName POSTresend_confirmmail
    # @apiGroup User
    # @apiDescription resend confirmation mail to user after registeration.
    # @apiExample Example usage:
    # curl -X POST  http://localhost:3000/api/v1/resend_confirmmail -H 'cache-control: no-cache' -H 'content-type: application/json' -d '{"email": "engamira333@gmail.com"}' 
    #
    # @apiSuccessExample Success-Response:
    # HTTP/1.1 200 OK
    # {
    #    "result : true"
    # }
    #
    # @apiError required_parameter_missing wrong email .
    #
    #  @apiErrorExample Response (example):
    #     HTTP/1.1 400 Badrequest
    #     {
    #       "result : false"
    #       "error": "MissingData"
    #       "status": 400- Bad Request
    #    }
    # =end 

  def resend_confirmmail
    @email = params[:email]
    @user = User.where("email =?",@email ).first     
      if @user
         @verify_code = Verification.where("user_id =?",@user.id ).first      
         UserMailer.confirmmail(@user,@verify_code.email_confirmation_token).deliver_later
         render json: {'result' => true}
      else
         render json: {'result' => false, 'error' => 'Email Not Found'}
      end
  end

    # POST /users
    # POST /users.json
    # =begin
    # @api {post} /users/ Create new User
    # @apiVersion 0.3.0
    # @apiName postUser
    # @apiGroup User
    # @apiDescription create new user.
    # @apiParam {String}     firstname         User's First Name 
    # @apiParam {String}     lastname          User's Last Name 
    # @apiParam {Integer}    country_id        User's Country 
    # @apiParam {String}     email             User's Email
    # @apiParam {String}     username          User's Username
    # @apiParam {String}     password          User's Password
    # @apiParam {String}     refered_by        Invitation Code Of the Invitor
    #
    # @apiExample Example usage:       
    # curl -X POST  http://localhost:3000/api/v1/users -H 'cache-control: no-cache' -H 'content-type: application/json' -d '{"user": {"firstname": "amira2","lastname": "amira2","password": "Amira123456", "country_id": 1,"email": "tessst@gmail.com","username": "EngineeraAmira2", "refered_by": "71000e83"}}' 
    # @apiSuccess {Integer}     id                   Users-ID.
    # @apiSuccess {String}      username             Users username.
    # @apiSuccess {String}      firstname            Users firstname.
    # @apiSuccess {String}      lastname             Users lastname.
    # @apiSuccess {String}      email                Users email.
    # @apiSuccess {Integer}     country_id           Users country.
    # @apiSuccess {String}      secret_code          Users Secret Code
    # @apiSuccess {String}      telephone            Users telephone
    # @apiSuccess {Integer}     account_currency     Users currency
    # @apiSuccess {Integer}     active_otp           Users active two factor authentication
    #
    # @apiSuccessExample Response (example):
    #     HTTP/ 200 OK
    #     {
    #       "success": "200 ok"
    #    }
    #
    # @apiError NoAccessRight Only authenticated users can create User.
    #
    # @apiError MissingToken invalid-token.
    # @apiErrorExample Error-Response:
    #     HTTP/1.1 400 Bad Request
    #     {
    #       "error": "Missing Token"
    #    }
    # =end

  def create
    @user = User.new(user_params)
    @user.uuid = SecureRandom.hex(4)
    @user.invitation_code = SecureRandom.hex(4)
    @user.auth_token = SecureRandom.hex(6)
    @token = SecureRandom.hex(4)
    respond_to do |format|
        if @user.save        
          @acc_num =  "PS1" + "%08d" % @user.id.to_i 
          @user.update(:account_number => @acc_num)
          Verification.create(:user_id => @user.id,:email_confirmation_token => @token)
          Watchdog.create(:user_id => @user.id,:ipaddress => request.env['REMOTE_ADDR'],:logintime => Time.now,:lastvisit => Time.now ,:operation_type => "sign_up")
          if (params[:user][:refered_by] != nil )
              @invited_by = User.where("invitation_code =? ",params[:user][:refered_by]).first
              if (@invited_by != nil)
                 AffilateProgram.create(:user_id => @user.id, :refered_by => @invited_by.id)
              end
          end
          UserMailer.confirmmail(@user,@token).deliver_later
          format.json { render json: @user, status: :created } 
          # format.json { render :show, status: :created, location: @user }
        else
        format.json { render json: @user.errors, status: :unprocessable_entity }
        end
    end
  end

    # PATCH/PUT /users/1
    # PATCH/PUT /users/1.json
    # =begin
    # @api {put} /users/:id/edit Update User 
    # @apiVersion 0.3.0
    # @apiName PutUser
    # @apiGroup User
    #
    # @apiDescription update details of a user.
    #
    # @apiParam {String}     username             Users username.
    # @apiParam {String}     firstname            Users firstname.
    # @apiParam {String}     lastname             Users lastname.
    # @apiParam {String}     email                Users email.
    # @apiParam {Integer}    country_id           Users country.
    # @apiParam {String}     secret_code          Users Secret Code
    # @apiParam {String}     telephone            Users telephone
    # @apiParam {Integer}    account_currency     Users currency
    # @apiParam {Integer}    active_otp           Users active two factor authentication 
    #
    # @apiExample Example usage:
    # curl -X PUT http://localhost:3000/api/v1/users/10 -H "Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMX0.ikUiajq9UFTi4OJDDGR2Xqk79U5vtiRWJaa8HgneqC4" -H 'cache-control: no-cache' -H 'content-type: application/json' -d '{ "email": "amira@ggggg.com"}'
    #
    # @apiSuccess {Integer}      id                     Users-ID.
    # @apiSuccess {String}       username               Users username.

app/controllers/clearance/users_controller.rb
class Clearance::UsersController < Clearance::BaseController
    if respond_to?(:before_action)
      before_action :redirect_signed_in_users, only: [:create, :new]
      skip_before_action :require_login, only: [:create, :new], raise: false
      skip_before_action :authorize, only: [:create, :new], raise: false
    else
      before_filter :redirect_signed_in_users, only: [:create, :new]
      skip_before_filter :require_login, only: [:create, :new], raise: false
      skip_before_filter :authorize, only: [:create, :new], raise: false
    end
    skip_before_action :check2fa ,only: [:new, :destroy, :create]
    skip_before_action :check_active_session ,only: [:new, :destroy, :create]

  
    def new
      @user = user_from_params
      render template: "users/new"
    end
  
    def create
      @user = user_from_params
  
      if @user.save
        sign_in @user
        redirect_back_or url_after_create
      else
        render template: "users/new"
      end
    end
  
    private
  
    def avoid_sign_in
      warn "[DEPRECATION] Clearance's `avoid_sign_in` before_filter is " +
        "deprecated. Use `redirect_signed_in_users` instead. " +
        "Be sure to update any instances of `skip_before_filter :avoid_sign_in`" +
        " or `skip_before_action :avoid_sign_in` as well"
      redirect_signed_in_users
    end
  
    def redirect_signed_in_users
      if signed_in?
        redirect_to Clearance.configuration.redirect_url
      end
    end
  
    def url_after_create
      Clearance.configuration.redirect_url
    end
  
    def user_from_params
      email = user_params.delete(:email)
      password = user_params.delete(:password)
  
      Clearance.configuration.user_model.new(user_params).tap do |user|
        user.email = email
        user.password = password
      end
    end
  
    def user_params
      params[Clearance.configuration.user_parameter] || Hash.new
    end
  end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<%= debug params%>

app/views/users/edit_password.html.erb
<h1>Editing User Password </h1>
    <%= form_for @user do |form| %>
        <% if @user.errors.any? %>
           <div id="error_explanation">
               <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
               <ul>
                   <% @user.errors.full_messages.each do |message| %>
                       <li><%= message %></li>
                   <% end %>
               </ul>
           </div>
       <% end %>

       <div class="password-field">
            <%= form.label :password %>
            <%= form.password_field :password %>
       </div><br>

       <div class="password-field">
            <%= form.label :confirm_password %>
            <%= form.password_field :confirm_password %>
       </div><br>

       <div class="submit-field">
             <%= form.submit  %>
       </div>
    <% end %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/get_two_factor.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Payers - Payment Facilator</title>
  <meta name="description" content="Admin, Dashboard, Bootstrap, Bootstrap 4, Angular, AngularJS" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimal-ui" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <!-- for ios 7 style, multi-resolution icon of 152x152 -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-barstyle" content="black-translucent">
  <link rel="apple-touch-icon" href="/assets/images/logo.png">
  <meta name="apple-mobile-web-app-title" content="Flatkit">
  <!-- for Chrome on Android, multi-resolution icon of 196x196 -->
  <meta name="mobile-web-app-capable" content="yes">
  <link rel="shortcut icon" sizes="196x196" href="/assets/images/logo.png">
  
  <!-- style -->
  <link rel="stylesheet" href="/assets/animate.css/animate.min.css" type="text/css" />
  <link rel="stylesheet" href="/assets/glyphicons/glyphicons.css" type="text/css" />
  <link rel="stylesheet" href="/assets/font-awesome/css/font-awesome.min.css" type="text/css" />
  <link rel="stylesheet" href="/assets/material-design-icons/material-design-icons.css" type="text/css" />

  <link rel="stylesheet" href="/assets/bootstrap/dist/css/bootstrap.min.css" type="text/css" />
  <!-- build:css ../assets/styles/app.min.css -->
  <link rel="stylesheet" href="/assets/styles/app.css" type="text/css" />
  <!-- endbuild -->
  <link rel="stylesheet" href="/assets/styles/font.css" type="text/css" />
</head>
<body>
  <div class="app" id="app">
  <% flash.each do |key, value| -%>
    <div class="col-sm-3">
            <div class="box-color accent pos-rlt">
              <span class="arrow bottom b-accent"></span>
              <div class="box-body">
                 <div id="flash_<%= key %>"><%=h value %></div>
              </div>
            </div>
    </div>
  <% end %>
<!-- ############ LAYOUT START-->
  <div class="center-block w-xxl w-auto-xs p-y-md">
    <div class="navbar">
      <div class="pull-center">
        <div ui-include="'/views/blocks/navbar.brand.html'"></div>
      </div>
    </div>
    <div class="p-a-md box-color r box-shadow-z1 text-color m-a">
	  <div class="m-b text-sm">
		<% if current_user.active_otp == 1%>
			Email Code Authentication
		<% else %>
			Google Authentication
		<% end %>
        
      </div>
      <%= form_for :confirm , :url => two_factor_path do |f| %>
		<div class="md-form-group float-label">
		  <%= f.text_field :code , class: 'md-input', :required => true %>
          <label>Authentication Code</label>
        </div>
              
        <button type="submit" class="btn primary btn-block p-x-md">Send</button>
	  <% end %>
    </div>
    <% if current_user.active_otp == 2 %>
        <div class="p-v-lg text-center">
            <div class="m-b"><a ui-sref="access.forgot-password" href="/send_confirmation_email" class="text-primary _600">has a problem with google authentication?, confirm by Email</a></div>		
		</div>
	<% end %>   
    
  </div>

  <div class="p-v-lg text-center">
      <div><a ui-sref="access.signin" href="" class="text-primary _600"><%= button_to "Sign Out", sign_out_path, method: :delete, class: "btn btn-sm accent"%></a></div>
  </div>

<!-- ############ LAYOUT END-->

  </div>
<!-- build:js scripts/app.html.js -->
<!-- jQuery -->
  <script src="/libs/jquery/jquery/dist/jquery.js"></script>
<!-- Bootstrap -->
  <script src="/libs/jquery/tether/dist/js/tether.min.js"></script>
  <script src="/libs/jquery/bootstrap/dist/js/bootstrap.js"></script>
<!-- core -->
  <script src="/libs/jquery/underscore/underscore-min.js"></script>
  <script src="/libs/jquery/jQuery-Storage-API/jquery.storageapi.min.js"></script>
  <script src="/libs/jquery/PACE/pace.min.js"></script>

  <script src="scripts/config.lazyload.js"></script>

  <script src="/scripts/palette.js"></script>
  <script src="/scripts/ui-load.js"></script>
  <script src="/scripts/ui-jp.js"></script>
  <script src="/scripts/ui-include.js"></script>
  <script src="/scripts/ui-device.js"></script>
  <script src="/scripts/ui-form.js"></script>
  <script src="/scripts/ui-nav.js"></script>
  <script src="/scripts/ui-screenfull.js"></script>
  <script src="/scripts/ui-scroll-to.js"></script>
  <script src="/scripts/ui-toggle-class.js"></script>

  <script src="/scripts/app.js"></script>

  <!-- ajax -->
  <script src="/libs/jquery/jquery-pjax/jquery.pjax.js"></script>
  <script src="/scripts/ajax.js"></script>
<!-- endbuild -->
</body>
</html>

app/views/users/post_two_factor.html.erb
<%= debug @user_code%>
<%= debug @sent_code %>

app/views/users/show.html.erb
<div class="padding">
  
      <div class="box">
        <div class="box-header">
          <span class="label danger pull-right"><%= @user.id %></span>
          <h3>User Profile</h3>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th>Username</th>
              <td><%= @user.username %></td>
            </tr>
          </thead>
          <tbody>
          <% if @user.avatar.attached? %>
            <tr>
              <th>Profile Picture</th>
              <td> <%= image_tag @user.avatar.variant(resize: "100x100")  %></td>
            </tr>
          <% end %>
            <tr>
              <th>firstname</th>
              <td> <%= @user.firstname %></td>
            </tr>
            <tr>
              <th>lastname</th>
              <td> <%= @user.lastname %></td>
            </tr>
            <tr>
              <th>Email</th>
              <td> <%= @user.email %></td>
            </tr>
            <tr>
              <th>account_number</th>
              <td> <%= @user.account_number %></td>
            </tr>
            <tr>
              <th>uuid</th>
              <td> <%= @user.uuid %></td>
            </tr>
            <tr>
              <th>telephone</th>
              <td> <%= @user.telephone %></td>
            </tr>
            <tr>
              <th>roleid</th>
              <td> <%= @user.roleid %></td>
            </tr>
            <tr>
              <th>country</th>
              <td> <%= @user.country.Full_Name %></td>
            </tr>
            <tr>
              <th>Account Currency</th>
                <% if !(@user.account_currency)%>
                   <td> <%= "USD" %></td>
                <% else %>
                   <td> <%= @user.country.Currency %></td>
                <% end%>
            </tr> 
          <% if @user.secret_code != nil and @user.secret_code != "" %>                
            <tr>
              <th>Secret Code</th>
              <td><%= "********" + @user.secret_code[@user.secret_code.length - 3 ,3] %></td>
            </tr> 
          <% end %>                
            <tr>
              <th>Active Otp</th>
              <% if @user.active_otp == 1 %>
                  <td> <%= "Email Code" %></td>
              <% elsif @user.active_otp == 2 %>
                  <td> <%= "Google Authentication Code" %></td>
              <% end %>              
            </tr>
            <tr>
              <th>Invitation Code</th>
              <td> <%= @user.invitation_code %></td>
            </tr>
            <tr>
              <th>Invitation Link</th>
              <td><%= "https://clearance.herokuapp.com/affilate-program/" + @user.invitation_code %></td>
            </tr>
            <tr>
              <th>Send Invitation Mail</th>
              
              <td> <%= form_for :invitiation, url: send_invitation_email_path do |form| %> 
                <div class="row">
               <div class="col-lg-4">
                      <div class="text-field">
                         <%= form.label :email %>
                         <%= form.text_field :email %>
                      </div>
                      </div>
                      <div class="col-lg-1">          
                      <button type="submit" style="padding:5px;height:30px;width:50px;background-color:#6887ff !important; border-color:#6887ff" class="btn btn-primary waves-effect waves-light m-t-15 text-center"><%= 'send' %> </button>
                      </div></div> <% end %></td>
            </tr>
            <% if @user.nationalid_verification != nil %>
              <tr>
                 <th>National ID Verification</th>
                 <td> <%= link_to 'show National Id Verification'.html_safe, { :controller => :nationalid_verifications,:action=>:show,:id => @user.nationalid_verification.id} %></td>
              </tr>
            <% end %>
            <% if @user.address_verification != nil %>
              <tr>
                 <th>Address Verification</th>
                 <td><%= link_to 'show Address Verification'.html_safe, { :controller => :address_verifications,:action=>:show,:id => @user.address_verification.id} %></td>
              </tr>
            <% end %>
            <% if @user.selfie_verification != nil %>
              <tr>
                 <th>Selfie Verification</th>
                 <td> <%= link_to 'show Selfie Verification'.html_safe, { :controller => :selfie_verifications,:action=>:show,:id => @user.selfie_verification.id} %></td>
              </tr>
            <% end %>
            
            <tr>
              <th>Other Links</th>
              <td> <%= link_to 'Edit Profile', edit_user_path(@user) %> - <%= link_to 'show user log'.html_safe, { :controller => :watchdogs,:action=>:user_log,:id => @user.id} %> - <%= link_to t('show active sessions').html_safe, { :controller => :logins,:action=>:active_sessions,:id => @user.id} %> - </td>
            </tr>
            
                    
           
          </tbody>
        </table>
      </div>
</div>

app/views/users/statistics.html.erb
<div class="card" style="width:20%; height:60%; background:#afb8cf; box-shadow: 0 0 8px #5c558d; margin-bottom:20px; padding-bottom:10px; padding-top:5px; margin-top:20px;">
<%= form_tag  url_for(:controller => 'users', :action => 'statistics'), :method => 'get' do %>

    <div class="page-title l-height-md mrg-bottom-md">
        <div class="row row-default button-row">
            <div class="col-md-3">
                <h4 class="iblock mrg-left-lg md-lg-fontsize text-dbrand font-weight-normal">
                    <%= t('Users statistics') %>
                </h4>
            </div>
            <div class="col-md-9">
                <div class="clearfix">                                        
                    <div class="field">                                   
                    <%= select_tag(:account_status, options_for_select([["جميع الأعضاء","count_users"],["الأعضاء المفعلين","confirmed"],["الأعضاء الموقوفين","disabled"]]),:include_blank =>  t('choose from list'))%>
                        <br><br><button type="submit" style="margin-top: -7px" class="btn btn-primary waves-effect waves-light m-t-15 text-center"><%= 'search' %> </button>
                    </div>    
                </div>
            </div>
        </div>
    </div>    
<% end %>
  <br>
<%= "sum = " + @result.count.to_s%>
</div>
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @result.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% if user.disabled == 0 %>
        <td><%= link_to t('Disable User').html_safe, { :controller => :users,:action=>:lock_unlock_account,:id => user.id} %></td>
        <% else %>
        <td><%= link_to t('Enable User').html_safe, { :controller => :users,:action=>:lock_unlock_account,:id => user.id} %></td>
        <% end %>
        <td><%= link_to t('show user log').html_safe, { :controller => :watchdogs,:action=>:user_log,:id => user.id} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<script language="JavaScript" type="text/javascript" src="/assets/js/jquery-3.2.1.min.js"></script>

<script>
$(document).ready(function() {
    $("#account_status").val("<%= params[:account_status].to_s%>");
    })
</script>

app/views/users/update.html.erb
<%= debug params %>
<%= debug params[:user][:confirm_password] %>
<%= debug params[:confirm_password] %>